### ISSUE TITLE
3대운동 500이하 언더아머 입어도 되나요?

### ISSUE THREAD

**Issue by taeguk** [dbdydgur2244/GoodForHealth#1]
3대운동 500이하는 언더아머를 입지 않는게 Best Practice 라고 알고 있는데 사실인가요?

**Comment by dbdydgur2244** [comment]
@taeguk,
이것은 마치 프로그래머의 기본이 자료 구조라고 알고 있는데 사실인가요? 라는 것과 비슷한 질문입니다.
언더아머의 길은 멀고도 험합니다.

**Comment by fuzzythecat** [comment]
당연히 안됩니다. 이슈 닫아주세요 😞

**Comment by JimJeon** [comment]
+1
