### ISSUE TITLE
손목 건강에 대한 내용들이 추가되었으면 좋겠습니다.

### ISSUE THREAD

**Issue by taeguk** [dbdydgur2244/GoodForHealth#2]
손목 건강 및 손목 강화/재활 운동에 대한 내용이 추가되면 좋겠습니다. 자료조사 및 연구가 필요로 합니다

**Comment by dbdydgur2244** [comment]
@taeguk 
손목도 좋군요. 이 부분은 `REAMDE.md`보다는 `Wiki` 페이지에서 자료 조사를 하여 다루도록 하겠습니다.

**Comment by LamFSangUk** [comment]
손목 지지 보조 기구 추천좀 해주세요.

**Comment by dbdydgur2244** [comment]
@LamFSangUk,
어떤 유릥 손목 지지대를 말하는건가여?

**Comment by dbdydgur2244** [comment]
@taeguk,
생각보다 너무 잡다한 영상, 지식들이 많아서 검색 결과 가장 따라하기 쉽고 효과적인 것 같은 내용만 넣었습니다.

**Comment by dbdydgur2244** [comment]
@LamFSangUk,
기구는 효과적인게 별로 없는 듯 싶네여
손목 보호대나 인체공학적 키볻, 마우스를 쓰시길

**Comment by taeguk** [comment]
@dbdydgur2244  감사합니다.
