### ISSUE TITLE
삼두만들고싶어요

### ISSUE THREAD

**Issue by ddyokim** [dbdydgur2244/GoodForHealth#3]
현재 제 팔뚝 상태가 김국진씨와 비슷한데 이종석 팔뚝을 만들고 싶습니다.

**Comment by fuzzythecat** [comment]
추천드리는 방법은 이종석씨의 팔뚝을 김국진씨와 비슷하게 만드는 것입니다.

**Comment by dbdydgur2244** [comment]
@ddyokim, 
@fuzzythecat님의 얘기처럼 하셔도 됩....
저도 요새 삼두삼두삼두 운동을 막 하려고 하고 있으니 정리해보겠습니다.

**Comment by dbdydgur2244** [comment]
@ddyokim 정리하여서 올렸습니다.
말발굽 같은 삼두를 얻어봅시다.
